INSERT INTO `abm_customsearch` (`oldPname`, `accession_number_general`, `description`, `catno`, `gene_name`, `gene_full_name`, `alias`, `list_of_species`, `unit_quantity`, `vector`, `titer`, `system`, `insert_size`, `filter_promoter`, `tag`, `serotype`, `vector_size`, `chromosome_location`, `format_general`, `oos_message`, `storage_condition`, `shipping_conditions`, `lead_time`, `disclaimer_general`, `guarantee`)
VALUES
('PLCB2 AAV (Human) (hSync) (CBH-GFP) (AAV Serotype 1)',
'BC000939',
'This ready-to-use AAV is part of abm’s AAV Expression System and can be used directly to transiently over-express your gene of interest in a wide range of host cells or animal models.',
'369401012211',
'PLCB2',
'phospholipase C, beta 2',
'FLJ38135, FLJ38135',
'Human',
'5 x 200 μl',
'pAAV-G-hSyn-CBH-gcGFP-hGH-amp',
'>1 x 10<sup>9</sup> GC/ml',
'AAV Virus',
'1830',
'hSyn',
'gcGFP',
'AAV Serotype 1',
'5532',
'15Q15.1',
'virus',
'1-3 Weeks',
'Store AAV viruses at -80°C. Avoid repeated freeze-thaw cycles by storing in small aliquots.',
'AAV viruses are shipped with dry ice. For long term storage, it is recommended to store the viruses at -80°C in small aliquots to avoid repeated freeze-thaw cycles.',
'Inquire',
'We will provide qPCR based titer evaluation for standard AAV virus orders as determination of successful packaging. In addition, if your virus has a GFP or RFP reporter (with no induction required for expression), we will also perform viral infectivity testing in our standard evaluation cell line - HEK293T. An image of the infectivity results will be provided on the CoA. Since infectivity is serotype dependent, and HEK293T cells do not infect well with Serotypes 4,5 and 6, an infectivity test will not be provided for these serotypes. In such cases, qPCR titer evaluation will be used as the final parameter to determine successful viral packaging.',
'abm guarantees that the correct ORF construct is provided and the mRNA expression is displayed upon successful transduction. If this is not the case, we will provide a one-time replacement. Customers must provide adequate data to show >80% transfection efficiency with a positive control, plus additional qPCR data or a western blot to evaluate the level of gene expression. The replacement will not be covered by the same guarantee. Please note that due to the large number of variables applicable, any further expression analysis (e.g. protein expression) is not covered by the guarantee, as such analysis is dependent on the end user\'s experimental conditions.');
