/*
Navicat MySQL Data Transfer

Source Server         : BitnamiAWS
Source Server Version : 50718
Source Host           : localhost:3306
Source Database       : bitnami_magento

Target Server Type    : MYSQL
Target Server Version : 50718
File Encoding         : 65001

Date: 2018-12-07 16:19:41
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for z5_vin
-- ----------------------------
DROP TABLE IF EXISTS `z5_vin`;
CREATE TABLE `z5_vin` (
  `sku` varchar(25) NOT NULL,
  `attribute_set_name` varchar(255) DEFAULT NULL COMMENT 'Attribute Set Name'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of z5_vin
-- ----------------------------
INSERT INTO `z5_vin` VALUES ('E001', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E002', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E005', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E006', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E007', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E008', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E009', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E010', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E011', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E012', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E013', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E014', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E015', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E016', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E017', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E018', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E020', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E024', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E026', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E027', 'Proteases');
INSERT INTO `z5_vin` VALUES ('E028', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E031', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E038', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E039', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E040', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E041', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E042', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E048', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E049', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E050', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E051', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E052', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E053', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E054', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E055', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E056', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E057', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E058', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E059', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E060', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E061', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E062', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E063', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E064', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E065', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E070', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E071', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E080', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E081', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E086', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E087', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E088', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E089', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E090', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E201', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E202', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E203', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('E204', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G008', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G009', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G010', 'dntps_ntps');
INSERT INTO `z5_vin` VALUES ('G011', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G012', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G013', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G013-Dye', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G014', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G014-Dye', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G018-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G019-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G020-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G021', 'Antibiotics');
INSERT INTO `z5_vin` VALUES ('G022', 'Antibiotics');
INSERT INTO `z5_vin` VALUES ('G023', 'Antibiotics');
INSERT INTO `z5_vin` VALUES ('G025', 'Western Blotting Reagents');
INSERT INTO `z5_vin` VALUES ('G028', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G030', 'Chemicals for Molecular Biology');
INSERT INTO `z5_vin` VALUES ('G031', 'Western Blotting Reagents');
INSERT INTO `z5_vin` VALUES ('G032', 'Western Blotting Reagents');
INSERT INTO `z5_vin` VALUES ('G034', 'Western Blotting Reagents');
INSERT INTO `z5_vin` VALUES ('G036-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G039', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G040', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G041-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G043-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G050', 'dntps_ntps');
INSERT INTO `z5_vin` VALUES ('G065', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G065-1', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G065-10', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G065-11', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G065-12', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G065-2', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G065-3', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G065-4', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G065-5', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G065-6', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G065-7', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G065-8', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G065-9', 'PCR Optimization');
INSERT INTO `z5_vin` VALUES ('G077-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G078', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G093-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G094-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G096-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G098-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G099', 'Transfection Reagents');
INSERT INTO `z5_vin` VALUES ('G124', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G124-Dye', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G126', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G148-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G163-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G164-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G174', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G174-Dye', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G177', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G189-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G191-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G231', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G232', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G233', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G234', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G235', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G236', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G237', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G238', 'Cell Biology Reagents and Stem Cell Media');
INSERT INTO `z5_vin` VALUES ('G261', 'Antibiotics');
INSERT INTO `z5_vin` VALUES ('G262', 'Antibiotics');
INSERT INTO `z5_vin` VALUES ('G263', 'Antibiotics');
INSERT INTO `z5_vin` VALUES ('G269', 'miRNA Synthesis Kit');
INSERT INTO `z5_vin` VALUES ('G270', 'miRNA Synthesis Kit');
INSERT INTO `z5_vin` VALUES ('G277', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G278', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G280', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G280-Dye', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G281', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G282', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G283', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G284', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G285', 'Cell Biology Reagents and Stem Cell Media');
INSERT INTO `z5_vin` VALUES ('G286', 'Stem Cell Characterization Kits');
INSERT INTO `z5_vin` VALUES ('G287', 'Cell Biology Reagents and Stem Cell Media');
INSERT INTO `z5_vin` VALUES ('G398', 'Cell Biology Reagents and Stem Cell Media');
INSERT INTO `z5_vin` VALUES ('G451', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G452', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G453', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G454', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G456', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G457', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G460', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G461', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G462', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G463', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G464', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G464-Dye', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G465', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G466-1mg', 'Antibody');
INSERT INTO `z5_vin` VALUES ('G467', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G469', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G471-iC', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G471-LR', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G471-R', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G471-S', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G472', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G475', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G476', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G478', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G485', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G486', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G487', 'DNA RNA Cleaning');
INSERT INTO `z5_vin` VALUES ('G488', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G489', 'DNA RNA Cleaning');
INSERT INTO `z5_vin` VALUES ('G490', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G491', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G492', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G493-P', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G493-PC', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G493-PL', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G493-PS', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G497', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G497-Dye', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G498', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G499', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G590', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G900', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G900-dye', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G901', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G901-dye', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G902', 'miRNA Synthesis Kit');
INSERT INTO `z5_vin` VALUES ('G903', 'miRNA Synthesis Kit');
INSERT INTO `z5_vin` VALUES ('G904', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G905', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G906', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G906-dye', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G915', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G916', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G917-iC', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G917-LR', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G917-R', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G917-S', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G918-P', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G918-PC', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G918-PL', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G918-PS', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G923', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G924', 'Chemicals for Molecular Biology');
INSERT INTO `z5_vin` VALUES ('G927', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G928', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G929', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('G931', 'Other Viral Expression');
INSERT INTO `z5_vin` VALUES ('G932', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G934', 'Real Time PCR');
INSERT INTO `z5_vin` VALUES ('G937', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G938', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G939', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G939-Dye', 'DNA Polymerases');
INSERT INTO `z5_vin` VALUES ('G946', 'dntps_ntps');
INSERT INTO `z5_vin` VALUES ('G947L', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G947S', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G948', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G949', 'Other Viral Expression');
INSERT INTO `z5_vin` VALUES ('G950', 'DNA RNA Cleaning');
INSERT INTO `z5_vin` VALUES ('G952', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G953', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G954', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G960', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G961', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G963', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G964', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G965', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G966', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G967', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('G968', 'Enzymes');
INSERT INTO `z5_vin` VALUES ('K008', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K030', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K032', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K034', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K036', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K038', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K040', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K042', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K044', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K045', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K046', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K047', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K048', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K049', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K086', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K087', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K088', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K108', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K130', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K132', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K134', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K136', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K138', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K140', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K142', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K144', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K145', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K146', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K147', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K148', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K149', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K186', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K187', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('K188', 'Cas9 Proteins');
INSERT INTO `z5_vin` VALUES ('LV900', 'Other Viral Expression');
INSERT INTO `z5_vin` VALUES ('LV900-iC', 'Other Viral Expression');
INSERT INTO `z5_vin` VALUES ('LV900-LR', 'Other Viral Expression');
INSERT INTO `z5_vin` VALUES ('LV900-R', 'Other Viral Expression');
INSERT INTO `z5_vin` VALUES ('LV900-S', 'Other Viral Expression');
INSERT INTO `z5_vin` VALUES ('Mastermix-5C', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('Mastermix-5L', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('Mastermix-5P', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('Mastermix-5PC', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('Mastermix-5PL', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('Mastermix-5PM', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('Mastermix-5PS', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('Mastermix-5R', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('Mastermix-5S', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-EC', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-EL', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-ER', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-ES', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-iC', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-iC-XL', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-KC', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-KL', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-KR', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-KS', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-LR', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-LR-XL', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-mC', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-mL', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-mR', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-mS', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-P', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-PC', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-PL', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-PM', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-PS', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-R', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-R-XL', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-S', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-S-XL', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-U', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('MasterMix-U-XL', 'Lyssa_Test_2_qpcr');
INSERT INTO `z5_vin` VALUES ('TM020', 'Cell Biology Reagents and Stem Cell Media');
INSERT INTO `z5_vin` VALUES ('TM021', 'Cell Biology Reagents and Stem Cell Media');
INSERT INTO `z5_vin` VALUES ('TM022', 'Cell Biology Reagents and Stem Cell Media');
INSERT INTO `z5_vin` VALUES ('TM025', 'Cell Biology Reagents and Stem Cell Media');
INSERT INTO `z5_vin` VALUES ('Z100135', 'growth factors');
